layout_spectrum: 0.682508038705639
typography_spectrum: 0.3765171526984708
color:
  lightness: 0.8623894198377164
  brandColors:
    - '#DC3522'
    - '#D9CB9E'
    - '#374140'
    - '#2A2C2B'
    - '#1E1E20'
  saturation: 0.18900355309690578
  brandStrength: 0.7883665657364348
  rhythmicContrast: 0.5925715532431397
name: Coz Creations
analytics: {}
description: The beginnings of my innane ramblings
author:
  name: James Cosgrove
  email: j.cosgrove88@icloud.com
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: article
    html: >-
      <article><h1>Website Graphic Design Weymouth - Arise Web
      Design</h1><p>Website graphic design Weymouth: An important feature of
      your website, will be the images that you chose to help catch the eye. The
      images that you will use, can range from the graphics of the logo, to
      photo&apos;s that you wish to include to enhance your content.</p><img
      src="https://www.arisewebdesign.co.uk/wp-content/uploads/2013/03/271-Medium.jpg"></article>
    src: 'https://www.arisewebdesign.co.uk/wp-content/uploads/2013/03/271-Medium.jpg'
    metadata:
      author: []
      related: []
      publisher:
        url: 'https://www.arisewebdesign.co.uk'
        name: Arise Web Design
        favicon: 'https://www.arisewebdesign.co.uk/favicon.ico'
        domain: www.arisewebdesign.co.uk
      keywords: []
      description: >-
        Website graphic design Weymouth: An important feature of your website,
        will be the images that you chose to help catch the eye. The images that
        you will use, can range from the graphics of the logo, to photo's that
        you wish to include to enhance your content.
      app_links: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      isBasedOnUrl: >-
        https://www.arisewebdesign.co.uk/cost-web-designer-weymouth/website-graphic-design-weymouth/
      title: Website Graphic Design Weymouth - Arise Web Design
      datePublished: null
    title: Website Graphic Design Weymouth - Arise Web Design
    caption: >-
      Website graphic design Weymouth: An important feature of your website,
      will be the images that you chose to help catch the eye. The images that
      you will use, can range from the graphics of the logo, to photo's that you
      wish to include to enhance your content.
    text: !<tag:yaml.org,2002:js/undefined> ''
content_rating:
  adult: false
opengraph: {}
title: James Cosgrove
purpose:
  - type: contact
    url: 'mailto:j.cosgrove88@icloud.com'
    label: E-mail Me
url: 'https://thegrid.ai/coz/'
github: true
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/017c65b2-0271-499b-956f-7805e0c6da51.jpg
